### ISSUE TITLE
Make Timeout variable

### ISSUE THREAD

**Issue by soupdiver** [maschmann/php-ansible#11]
Currently the ProcessBuilder you use uses the default timeout. See: https://github.com/maschmann/php-ansible/blob/master/Ansible/Command/AbstractAnsibleCommand.php#L168

Playbooks can take longer than the default of 60 seconds but fail currently.
In my case:
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process ""/usr/bin/php5" artisan queue:work  --queue="ansible,k8s,aws" --delay=0 --memory=128 --sleep=3 --tries=0 --env=local" exceeded the timeout of 60 seconds.
```

So it would be cool if this value would be more flexible

**Comment by maschmann** [comment]
Ok, I'll add it to the milestones :+1:

**Comment by soupdiver** [comment]
I'm willing to create a PR because that's quite important to me :)
Would this API be ok with a default for timeout() of 60 if not explicitly set?
```php
 $ansible
        ->playbook()
       ->timeout(3600)
```

**Comment by maschmann** [comment]
btw. I've just checked for the timeout implementation: Ansible main class already has a setTimeout.
Default process timeout is 600s  (class constant) and can be overwritten by:

``` php
$ansible = new  Ansible( ... );
$ansible->setTimeout($newTimeout);
```
And will then be used for instantiating the symfony process component.

**Comment by soupdiver** [comment]
ahhhhh ok cool
overlooked that :)

thanks!

**Comment by maschmann** [comment]
No problem - I have to be honest: I haven't looked into the code for a few days now, since I'm under heavy load from my (work) projects. So I just plainly forgot about the setter. Added that recently because I had timeout problems in my deployment-platform project for which I implemented this lib ;-)
And the results of the the platform will most likely sum up into a symfony2 bundle where most of the basic config for playbook/galaxy will be abstracted into a bundle config.
