### ISSUE TITLE
Instructions on user permissions

### ISSUE THREAD

**Issue by back-2-95** [maschmann/php-ansible#31]
Hi,

I have setup Ubuntu 16.04 Vagrant machine with apache and php 7.
Then I have your code included in my application via composer.

Creating Ansible command works fine, but I get `Failed to connect to the host via ssh.` when command is executed. If I run the same command from terminal inside the Vagrant machine, it works fine. I have taken sure that keys are on place on the remote server.

Any instructions or clues? And these instructions could be at the readme.md.

Thanks!

**Comment by xabbuh** [comment]
Do you mean that you are executing the command outside your Vagrant box?

**Comment by back-2-95** [comment]
No, inside.

**Comment by back-2-95** [comment]
In PHP, if I test connecting like this, it works:

```
$process = new Process("ssh -t -v root@REMOTE_SERVER_IP -i ". $private_key_path .'');
        $process->run();
        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }

        $ssh_out = $process->getOutput();
        echo $ssh_out; exit;
```

**Comment by back-2-95** [comment]
So, it seems that SSH connections:

a) works if `www-data > php > ssh connection`

b) does not work if `www-data > php > ansible-playbook > ssh connection`

**Comment by back-2-95** [comment]
Maybe @maschmann could create example Vagrant file with provision to show working setup?

**Comment by maschmann** [comment]
@back-2-95 some questions first: it works if you connect to your machine and start the script manually? Is your ssh connection configured with key forwarding?
is your local (vm) connection to the remote host also configured with key forwarding?

I've had a similar problem with plain ansible usage via bash in my jenkins environment.
Environment: Virtual server, Debian 7
Every time ansible connected to the remote host, there was an authentication error. Caused by not finding the ssh-agent instance. I've circumvented that by creating a PID file with the PID of the user's ssh-agent process and then directly accessing it that way. If you like, I can paste you some code examples on monday when I'm back in my work env.

What you can do to investigate this: Add come verbosity to your ssh command. Try to start a ssh connection by e.g. bash script (ansible command) and then log your ssh connection verbosely. You'll notice authentication errors. If you try to acces the ssh-agent on a connection to your vm without key forwarding, you should have the same errors.
Took me around 2 days of research/ trial and error to fix this in our CI.

Not a bug in the lib :+1:

**Comment by back-2-95** [comment]
Hi,

Not a bug in the lib I know, I checked the code and I can see that. 👍 

1) yes, if I ´vagrant ssh´and go and run ansible playbook, it works
2) I have key forwarding from my OSX
3) vm to remote connection uses explicit private key when connecting

I have -vvvv on ansible commands but no breakthrough there.
The fail comes only when ansible is connecting. If I use plain command with Process (see above) it works or if I use PHP's [ssh functions](http://php.net/manual/en/function.ssh2-connect.php) to connect.

Currently in all methods I end up using following command:
´ansible-playbook -i /absolute/path/to/hosts /absolute/path/to/playbook.yml --user=root --private-key=/absolute/path/to/private_key´

I'll continue my research, happily it's on my own private time ;)

**Comment by back-2-95** [comment]
I got it working:

On my project, I have ansible.cfg and I added there the following line:
´´´
[ssh_connection]
control_path = /home/vagrant/.ansible/cp
´´´

At the time of discovery I was running apache service with ´vagrant´ user.

Then I changed back to user ´www-data´ and I got fail until I created a folder /var/www/.ansible and owned by www-data and changed control path point to that path.

Now my TODO is to check if I can make that control_path value point automatically to current user and which user I should use to run apache when running ansible.

**Comment by maschmann** [comment]
Good morning @back-2-95,

sounds like you're using apache with mod_php: I'd strongly suggest to switch to php-fpm for better security with your ansible setup! You'll have a separate (shell) user for your php fpm connection pool where you can put an ansible.cfg and encapsulate the ssh access.

Note: The vagfrant user has a lot more rights in that setup, compared to the apache (www-data) user. Using a separate user with /bin/sh access should do it.

**Comment by back-2-95** [comment]
Oh my, why did I not use php-fpm :)
Now when I tried it, it worked out-of-the-box.

Do you have some example on connection pool setup with the scenario you described with ansible.cfg?

**Comment by eriksays** [comment]
Jumping on this old thread. for running ansible tasks as the www user, I'm getting an error of "1" when I run this in the browser but via terminal no problems. I suspect this is a user permission error of the www user.
