### ISSUE TITLE
Create new 1.x branch and 1.2.0 release to include bug fixes.

### ISSUE THREAD

**Issue by jonpugh** [maschmann/php-ansible#41]
The changes 12 days ago to master broke support for php versions < 7.2. I don't think there were code changes that require the higher level of PHP.

Since the package switched to a 2.x version, you should create a 1.x branch and a new 1.2.0 release so that those of us still supporting php < 7.2 will be able to use this.

I created a new tag v1.2.0 on our fork for what seems like the right ref: right before the switch to `--become-user`. https://github.com/opendevshop/php-ansible/releases/tag/v1.2.0

Please create a 1.x branch and a 1.2.0 tag from ref 29a80ccd6f5dd71180d1e3d4110e5e3cc55cb8ee so that we can still use this without having to upgrade to php 7.2. 

Thanks!

**Comment by maschmann** [comment]
Hi @jonpugh,
normally such a BC breaking release is developed in a separate branch, merged into master and tagged as a new major release. Ok, this is an alpha/prerelease.
Creating an additional branch is only necessary if the older major (1.x) version would be further fixed/developed. Another tag to close the 1.x developement is fine with me :+1: Since the tag will work if you don't use the death star pendency or dev/master. 
I also checked the changes and will add another travis test for 7.1 (besides the dependency adjustments).

**Comment by jonpugh** [comment]
> Creating an additional branch is only necessary if the older major (1.x) version would be further fixed/developed.

Yeah, I know there won't be from now on, but there was development after the last 1.x release. 

Honestly I wouldn't care if the 2.x branch kept working with 7.0 and 5.6, despite outgoing support I think if it works, just leave the PHP dependency in composer.json as low as possible.

**Comment by maschmann** [comment]
Since there is no further activity here, I consider this closed
